import { Router } from "express";
import { asyncHandler } from "../../core/http/async-handler.js";
import { authenticate } from "../../middlewares/authenticate.js";
import { validate } from "../../middlewares/validate.js";
import { deleteDocumentController, downloadDocumentController, listLeadDocumentsController, uploadLeadDocumentController } from "./document.controller.js";
import { documentUpload } from "./document.upload.js";
import { documentParamsSchema, leadDocumentParamsSchema, uploadDocumentSchema } from "./document.validation.js";
const router = Router();
router.use(authenticate);
router.get("/leads/:leadId", validate(leadDocumentParamsSchema), asyncHandler(listLeadDocumentsController));
router.post("/leads/:leadId", documentUpload.single("file"), validate(uploadDocumentSchema), asyncHandler(uploadLeadDocumentController));
router.get("/:id/download", validate(documentParamsSchema), asyncHandler(downloadDocumentController));
router.delete("/:id", validate(documentParamsSchema), asyncHandler(deleteDocumentController));
export default router;
