import { z } from "zod";
const optionalEmail = z.union([z.literal(""), z.string().trim().email("Enter a valid email")]);
const optionalUrl = z.union([z.literal(""), z.string().trim().url("Enter a valid URL")]);
const num = z.union([z.literal(""), z.coerce.number().min(0)]);
export const leadFormSchema = z.object({
  companyName: z.string().trim().min(2, "Company name is required"),
  primaryContactName: z.string().trim().min(1, "Primary contact is required"),
  designation: z.string().trim().max(160).optional().default(""),
  email: optionalEmail,
  mobile: z.string().trim().max(32).optional().default(""),
  whatsapp: z.string().trim().max(32).optional().default(""),
  linkedinProfileUrl: optionalUrl,
  contacts: z.array(z.object({ fullName: z.string().trim().max(160).optional().default(""), designation: z.string().trim().max(160).optional().default(""), email: optionalEmail, mobile: z.string().trim().max(32).optional().default(""), whatsapp: z.string().trim().max(32).optional().default(""), linkedinProfileUrl: optionalUrl })).max(12).optional().default([]),
  industry: z.string().trim().min(2, "Industry is required"),
  subSector: z.string().trim().max(160).optional().default(""),
  businessModels: z.array(z.string()).optional().default([]),
  companySize: z.string().optional().default(""),
  employeeStrength: z.string().trim().max(80).optional().default(""),
  annualTurnover: num,
  estimatedBudget: num,
  country: z.string().trim().max(120).optional().default("India"),
  state: z.string().trim().max(120).optional().default(""),
  city: z.string().trim().max(120).optional().default(""),
  websiteUrl: optionalUrl,
  linkedinPostUrl: optionalUrl,
  postDate: z.string().optional().default(""),
  postContent: z.string().max(6000).optional().default(""),
  businessRequirementAnalysis: z.string().max(6000).optional().default(""),
  buyingIntentScore: z.coerce.number().int().min(0).max(100),
  leadPriority: z.enum(["High", "Medium", "Low"]),
  personalizedComment: z.string().max(3000).optional().default(""),
  firstMessage: z.string().max(4000).optional().default(""),
  salesStage: z.enum(["C1", "C2", "C3", "C4", "Won", "Lost"]),
  assignedTo: z.string().optional().default(""),
  source: z.enum(["LinkedIn", "Apollo", "Referral", "Website", "Event", "Cold Call", "Upwork", "Fiverr", "Google", "Advertisement", "Datapoint", "Other"]),
  temperature: z.enum(["Hot", "Warm", "Potential", "Cold"]),
  decisionMakers: z.string().max(3000).optional().default(""),
  companyOverview: z.string().max(6000).optional().default(""),
  painPointsText: z.string().max(4000).optional().default(""),
  internalComments: z.string().max(6000).optional().default(""),
  nextAction: z.string().max(1200).optional().default(""),
  nextFollowUpDate: z.string().optional().default(""),
  attachmentUrl: optionalUrl,
  researchNotes: z.string().max(6000).optional().default(""),
  followUp1Date: z.string().optional().default(""),
  followUp1Status: z.enum(["Pending", "Completed", "Skipped"]),
  followUp1Note: z.string().max(1000).optional().default(""),
  followUp2Date: z.string().optional().default(""),
  followUp2Status: z.enum(["Pending", "Completed", "Skipped"]),
  followUp2Note: z.string().max(1000).optional().default(""),
  followUp3Date: z.string().optional().default(""),
  followUp3Status: z.enum(["Pending", "Completed", "Skipped"]),
  followUp3Note: z.string().max(1000).optional().default(""),
});

const iso = (value) => value ? new Date(value).toISOString() : undefined;
export const formToLeadPayload = (values) => ({
  companyName: values.companyName,
  primaryContact: { fullName: values.primaryContactName, designation: values.designation || "", email: values.email || "", mobile: values.mobile || "", whatsapp: values.whatsapp || "", linkedinProfileUrl: values.linkedinProfileUrl || "" },
  contacts: (values.contacts || []).filter((item) => item.fullName || item.email || item.mobile).map((item) => ({ ...item, isPrimary: false })),
  industry: values.industry,
  subSector: values.subSector || "",
  businessModels: values.businessModels || [],
  companySize: values.companySize || "",
  employeeStrength: values.employeeStrength || "",
  annualTurnover: Number(values.annualTurnover || 0),
  estimatedBudget: Number(values.estimatedBudget || 0),
  country: values.country || "India",
  state: values.state || "",
  city: values.city || "",
  websiteUrl: values.websiteUrl || "",
  linkedinPostUrl: values.linkedinPostUrl || "",
  postDate: iso(values.postDate),
  postContent: values.postContent || "",
  businessRequirementAnalysis: values.businessRequirementAnalysis || "",
  buyingIntentScore: Number(values.buyingIntentScore || 0),
  leadPriority: values.leadPriority,
  personalizedComment: values.personalizedComment || "",
  firstMessage: values.firstMessage || "",
  salesStage: values.salesStage,
  ...(values.assignedTo ? { assignedTo: values.assignedTo } : {}),
  source: values.source,
  temperature: values.temperature,
  decisionMakers: values.decisionMakers || "",
  companyOverview: values.companyOverview || "",
  painPoints: (values.painPointsText || "").split(",").map((item) => item.trim()).filter(Boolean),
  internalComments: values.internalComments || "",
  nextAction: values.nextAction || "",
  nextFollowUpDate: iso(values.nextFollowUpDate),
  attachmentUrl: values.attachmentUrl || "",
  researchNotes: values.researchNotes || "",
  followUps: [1, 2, 3].map((sequence) => ({ sequence, scheduledAt: iso(values[`followUp${sequence}Date`]), status: values[`followUp${sequence}Status`], note: values[`followUp${sequence}Note`] || "" })).filter((item) => item.scheduledAt || item.note),
});

const localDateTime = (value) => value ? new Date(value).toISOString().slice(0, 16) : "";
export const leadToForm = (lead) => ({
  companyName: lead?.companyName || "", primaryContactName: lead?.primaryContact?.fullName || "", designation: lead?.primaryContact?.designation || "", email: lead?.primaryContact?.email || "", mobile: lead?.primaryContact?.mobile || "", whatsapp: lead?.primaryContact?.whatsapp || "", linkedinProfileUrl: lead?.primaryContact?.linkedinProfileUrl || "", contacts: (lead?.contacts || []).map((item) => ({ fullName: item.fullName || "", designation: item.designation || "", email: item.email || "", mobile: item.mobile || "", whatsapp: item.whatsapp || "", linkedinProfileUrl: item.linkedinProfileUrl || "" })),
  industry: lead?.industry || "", subSector: lead?.subSector || "", businessModels: lead?.businessModels || [], companySize: lead?.companySize || "", employeeStrength: lead?.employeeStrength || "", annualTurnover: lead?.annualTurnover || "", estimatedBudget: lead?.estimatedBudget || "", country: lead?.country || "India", state: lead?.state || "", city: lead?.city || "", websiteUrl: lead?.websiteUrl || "", linkedinPostUrl: lead?.linkedinPostUrl || "", postDate: lead?.postDate ? String(lead.postDate).slice(0, 10) : "", postContent: lead?.postContent || "", businessRequirementAnalysis: lead?.businessRequirementAnalysis || "", buyingIntentScore: lead?.buyingIntentScore ?? 0, leadPriority: lead?.leadPriority || "Medium", personalizedComment: lead?.personalizedComment || "", firstMessage: lead?.firstMessage || "", salesStage: lead?.salesStage || "C1", assignedTo: lead?.assignedTo?.id || "", source: lead?.source || "LinkedIn", temperature: lead?.temperature || "Warm", decisionMakers: lead?.decisionMakers || "", companyOverview: lead?.companyOverview || "", painPointsText: (lead?.painPoints || []).join(", "), internalComments: lead?.internalComments || "", nextAction: lead?.nextAction || "", nextFollowUpDate: localDateTime(lead?.nextFollowUpDate), attachmentUrl: lead?.attachmentUrl || "", researchNotes: lead?.researchNotes || "",
  ...Object.fromEntries([1,2,3].flatMap((n) => { const item = (lead?.followUps || []).find((x) => x.sequence === n); return [[`followUp${n}Date`, localDateTime(item?.scheduledAt)], [`followUp${n}Status`, item?.status || "Pending"], [`followUp${n}Note`, item?.note || ""]]; })),
});
export const emptyLeadForm = leadToForm(null);
