import { Router } from "express";
import authRoutes from "../features/auth/auth.routes.js";
import dashboardRoutes from "../features/dashboard/dashboard.routes.js";
import dealRoutes from "../features/deals/deal.routes.js";
import interactionRoutes from "../features/interactions/interaction.routes.js";
import documentRoutes from "../features/documents/document.routes.js";
import importRoutes from "../features/imports/lead-import.routes.js";
import integrationRoutes from "../features/integrations/integration.routes.js";
import profileRoutes from "../features/profile/profile.routes.js";
import leadRoutes from "../features/leads/lead.routes.js";
import targetRoutes from "../features/targets/target.routes.js";
import userRoutes from "../features/users/user.routes.js";
import healthRoutes from "./health.routes.js";
const router = Router();
router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/targets", targetRoutes);
router.use("/leads", leadRoutes);
router.use("/interactions", interactionRoutes);
router.use("/deals", dealRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/profile", profileRoutes);
router.use("/imports", importRoutes);
router.use("/documents", documentRoutes);
router.use("/integrations", integrationRoutes);
export default router;
