import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import Button from "../../../components/ui/Button";
import DatePicker from "../../../components/ui/DatePicker";
import Input from "../../../components/ui/Input";
import Select from "../../../components/ui/Select";
import TextArea from "../../../components/ui/TextArea";
import { c3FormSchema, c4FormSchema } from "../schemas/deal.schemas";

const dateOnly = (value) => value ? String(value).slice(0, 10) : "";
const c3Defaults = (lead, deal) => ({ budget: deal?.budget ?? lead?.estimatedBudget ?? 0, probability: deal?.probability ?? 0, expectedClose: dateOnly(deal?.expectedClose), v1Modules: deal?.versions?.find((x) => x.label === "V1")?.modules || "", v1Timeline: deal?.versions?.find((x) => x.label === "V1")?.timeline || "", v1Cost: deal?.versions?.find((x) => x.label === "V1")?.cost || 0, v2Modules: deal?.versions?.find((x) => x.label === "V2")?.modules || "", v2Timeline: deal?.versions?.find((x) => x.label === "V2")?.timeline || "", v2Cost: deal?.versions?.find((x) => x.label === "V2")?.cost || 0, v3Modules: deal?.versions?.find((x) => x.label === "V3")?.modules || "", v3Timeline: deal?.versions?.find((x) => x.label === "V3")?.timeline || "", v3Cost: deal?.versions?.find((x) => x.label === "V3")?.cost || 0, preferredVersion: deal?.preferredVersion || "", proposalVersion: deal?.proposalVersion || "", proposalStatus: deal?.proposalStatus || "PENDING", proposalUrl: deal?.proposalUrl || "", quotationUrl: deal?.quotationUrl || "", negotiationNotes: deal?.negotiationNotes || "" });
const c4Defaults = (deal) => ({ finalVersion: deal?.finalVersion || "", finalValue: deal?.finalValue || 0, discountPercent: deal?.discountPercent || 0, advanceAmount: deal?.advanceAmount || 0, paymentStatus: deal?.paymentStatus || "PENDING", dealStatus: deal?.dealStatus || "ACTIVE", finalScope: deal?.finalScope || "", paymentTerms: deal?.paymentTerms || "", agreementUrl: deal?.agreementUrl || "", ndaUrl: deal?.ndaUrl || "", poUrl: deal?.poUrl || "", agreementFileName: deal?.agreementFileName || "", customCommissionPercent: deal?.customCommissionPercent || 0, payoutStart: dateOnly(deal?.payoutStart), payoutMonths: deal?.payoutMonths || 0, approvedTimeline: deal?.approvedTimeline || "", closureNotes: deal?.closureNotes || "" });

function C3Fields({ register, errors }) { return <div className="deal-form-grid">
  <Input id="deal-budget" label="Budget (₹)" type="number" {...register("budget")} error={errors.budget?.message} /><Input id="deal-probability" label="Probability %" type="number" {...register("probability")} error={errors.probability?.message} /><DatePicker id="deal-close" label="Expected Close" {...register("expectedClose")} />
  {["1", "2", "3"].map((n) => <div className="deal-version-card" key={n}><strong>V{n} — Solution Version</strong><TextArea id={`v${n}-modules`} label="Modules Included" {...register(`v${n}Modules`)} /><Input id={`v${n}-timeline`} label="Timeline" {...register(`v${n}Timeline`)} /><Input id={`v${n}-cost`} label="Cost (₹)" type="number" {...register(`v${n}Cost`)} /></div>)}
  <Select id="preferred-version" label="Preferred Version" {...register("preferredVersion")}><option value="">Not decided</option><option>V1</option><option>V2</option><option>V3</option><option value="CUSTOM">Custom</option></Select>
  <Select id="proposal-version" label="Proposal Version" {...register("proposalVersion")}><option value="">Not selected</option><option>V1</option><option>V2</option><option>V3</option><option value="CUSTOM">Custom</option></Select>
  <Select id="proposal-status" label="Proposal Status" {...register("proposalStatus")}><option value="PENDING">Pending</option><option value="PREPARED">Prepared</option><option value="SHARED">Shared</option><option value="FEEDBACK_RECEIVED">Feedback Received</option><option value="REVISION_REQUIRED">Revision Required</option><option value="ACCEPTED">Accepted</option><option value="REJECTED">Rejected</option></Select>
  <Input id="proposal-url" label="Proposal URL" {...register("proposalUrl")} error={errors.proposalUrl?.message} /><Input id="quotation-url" label="Quotation URL" {...register("quotationUrl")} error={errors.quotationUrl?.message} /><TextArea id="negotiation" className="full-span" label="Negotiation / Commercial Notes" {...register("negotiationNotes")} />
</div>; }
function C4Fields({ register, errors }) { return <div className="deal-form-grid">
  <Select id="final-version" label="Final Selected Version" {...register("finalVersion")}><option value="">Not selected</option><option>V1</option><option>V2</option><option>V3</option><option value="CUSTOM">Custom</option></Select><Input id="final-value" label="Final Deal Value (₹)" type="number" {...register("finalValue")} /><Input id="discount" label="Discount %" type="number" {...register("discountPercent")} /><Input id="advance" label="Token / Advance (₹)" type="number" {...register("advanceAmount")} />
  <Select id="payment-status" label="Payment Status" {...register("paymentStatus")}><option value="PENDING">Pending</option><option value="PARTIAL">Partial</option><option value="RECEIVED">Received</option></Select><Select id="deal-status" label="Deal Status" {...register("dealStatus")}><option value="ACTIVE">Active</option><option value="WON">Won</option><option value="LOST">Lost</option><option value="ON_HOLD">On Hold</option><option value="CANCELLED">Cancelled</option></Select>
  <TextArea id="final-scope" className="full-span" label="Final Scope" {...register("finalScope")} /><TextArea id="payment-terms" className="full-span" label="Payment Terms" {...register("paymentTerms")} />
  <Input id="agreement-url" label="Agreement URL" {...register("agreementUrl")} error={errors.agreementUrl?.message} /><Input id="nda-url" label="NDA URL" {...register("ndaUrl")} error={errors.ndaUrl?.message} /><Input id="po-url" label="Purchase Order URL" {...register("poUrl")} error={errors.poUrl?.message} /><Input id="agreement-file" label="Agreement File Name" {...register("agreementFileName")} />
  <Input id="commission" label="Custom Commission %" type="number" {...register("customCommissionPercent")} /><DatePicker id="payout-start" label="Commission Payout Start" {...register("payoutStart")} /><Input id="payout-months" label="Delivery / Payout Months" type="number" {...register("payoutMonths")} /><Input id="approved-timeline" label="Approved Timeline" {...register("approvedTimeline")} /><TextArea id="closure-notes" className="full-span" label="Closure Notes" {...register("closureNotes")} />
</div>; }

function DealForm({ stage, lead, deal, saving, onSave, onCancel }) {
  const schema = stage === "C3" ? c3FormSchema : c4FormSchema; const defaults = stage === "C3" ? c3Defaults(lead, deal) : c4Defaults(deal);
  const { register, handleSubmit, reset, formState: { errors } } = useForm({ resolver: zodResolver(schema), defaultValues: defaults });
  useEffect(() => { reset(stage === "C3" ? c3Defaults(lead, deal) : c4Defaults(deal)); }, [stage, lead?.id, deal?.id, reset]);
  const submit = (values) => stage === "C3" ? onSave({ budget: values.budget, probability: values.probability, expectedClose: values.expectedClose || "", versions: [{ label: "V1", modules: values.v1Modules || "", timeline: values.v1Timeline || "", cost: values.v1Cost }, { label: "V2", modules: values.v2Modules || "", timeline: values.v2Timeline || "", cost: values.v2Cost }, { label: "V3", modules: values.v3Modules || "", timeline: values.v3Timeline || "", cost: values.v3Cost }], preferredVersion: values.preferredVersion, proposalVersion: values.proposalVersion, proposalStatus: values.proposalStatus, proposalUrl: values.proposalUrl || "", quotationUrl: values.quotationUrl || "", negotiationNotes: values.negotiationNotes || "" }) : onSave(values);
  return <form className="deal-form" onSubmit={handleSubmit(submit)}>{stage === "C3" ? <C3Fields register={register} errors={errors} /> : <C4Fields register={register} errors={errors} />}<div className="deal-form-actions"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" loading={saving}>Save {stage}</Button></div></form>;
}
export default DealForm;
